# Logging setup 
# Maximum of archive log files to keep.
logging.file.max-history=5 
# Maximum log file size. 
logging.file.max-size=2MB 


# Enable multipart uploads
spring.servlet.multipart.enabled=true
# Threshold after which files are written to disk.
spring.servlet.multipart.file-size-threshold=1MB
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=30MB
server.port=5502


spring.session.store-type=mongodb
spring.data.mongodb.host=127.0.0.1
spring.data.mongodb.port=27017
spring.data.mongodb.database=assessment


# timezone properties
#app.server.timezone-id=UTC
app.client.timezone-id=Asia/Kolkata

# email notification flow global control
app.notification.mode=disabled

#spring jobs
org.quartz.jobStore.class=org.quartz.simpl.RAMJobStore
using.spring.schedulerFactory=false

# bot user for job scheduler at tenant level
app.system-user-name=tenant-bot
app.system-user-password=p1YaQ504Z689

app.system.tenant=assessment.com